
CREATE TABLE roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    cargo VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    rol INT NOT NULL,
    token VARCHAR NOT NULL,
    FOREIGN KEY (rol) REFERENCES roles(id) ON DELETE CASCADE
);
